# Generated by Django 2.1.7 on 2019-03-06 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0016_auto_20190221_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='markdown_reason',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
